[package]
name = "rikkabot-rust"
version = "0.1.0"
authors = ["Peter Cai <peter@typeblog.net>"]

[dependencies]
error-chain = "0.11"
hyper = "0.11"
hyper-tls = "0.1"
tokio-core = "0.1"
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
percent-encoding = "1.0.1"